server:
  port: 8082



spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: Auth_Service
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect


logging:
  level:
    org.springframework.security.web: DEBUG


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: true
    fetch-registry: true